name: CI
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install node
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm run test

  build_and_push:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4

      - name: Login to docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }} # Create repo secret in github instead of environment secret
          password: ${{ secrets.DOCKER_PASSWORD }} # Create repo secret in github instead of environment secret

      - name: Build docker image
        run: docker build -t sample-express/nodejs-app:latest .

      - name: Push docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/sample-nodejs-app:latest
