name: CI
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: install node
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: install dependencies
        run: npm install

      - name: Run tests
        run: npm run test

  build_and_push:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4

      - name: build docker image
        run: docker build -t sample-express/nodejs-app:latest .

      - name: login to docker hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: push docker image
        run: docker push sample-express/nodejs-app:latest
